p4-sciencequiz-erinsusanthomas-main/config/routes.rb
Rails.application.routes.draw do

  # Generated routes
  resources :organizations
  resources :teams
  resources :students

  # Routes for student_teams
  get 'student_teams/new',             to: 'student_teams#new',       as: :new_student_team
  post 'student_teams',                to: 'student_teams#create',    as: :student_teams
  patch 'student_teams/:id/terminate', to: 'student_teams#terminate', as: :terminate_student_team
  delete 'student_teams/:id',          to: 'student_teams#destroy',   as: :remove_student_team

  # Semi-static page routes
  get 'home',         to: 'home#index',   as: :home
  get 'home/about',   to: 'home#about',   as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

p4-sciencequiz-erinsusanthomas-main/app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    <strong>Add a New <%= model_name.capitalize %></strong>
  <% end %>

p4-sciencequiz-erinsusanthomas-main/app/views/partials/_address.html.erb
<p>
  <%= organization.street_1 %><br>
  <% unless organization.street_2.nil? %>
    <%= organization.street_2 %><br>
  <% end %>
  <%= organization.city %>, <%= organization.state %> <%= organization.zip %>
</p>

p4-sciencequiz-erinsusanthomas-main/app/views/partials/_display_base_errors.html.erb
<% unless object.errors.empty? %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning">
    <%= object.errors[:base].first %>
  </div>
<% end %>

p4-sciencequiz-erinsusanthomas-main/app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <%= msg %>
  </div>
<% end %>

p4-sciencequiz-erinsusanthomas-main/app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer" class="center-align">
  
  <%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About ScienceQuiz', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Contact ScienceQuiz', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Privacy Policy', privacy_path %>
  <br />
  <div id="copy">
    Webmaster: <%= mail_to("yourandrewid@andrew.cmu.edu", "YOUR NAME HERE", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2021
  </div>

</div>

p4-sciencequiz-erinsusanthomas-main/app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
            </div>
          </div>
          <p>&nbsp;</p>
          <div class="row">
            <div class="form-actions col s9">
              <%= f.button :submit %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', :back %>

p4-sciencequiz-erinsusanthomas-main/app/views/partials/_index_structure.html.erb
<div class="row">
  <% if sidebar.blank? %>
    <div class="col s9">
  <% else %>
    <div class="col s8">
  <% end %>
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <% unless sidebar.blank? %>
  <div class="col s4">
      <!-- render the sidebar, if it exists -->
      <%= render partial: "#{sidebar}" %>
    </div>
  <% end %>
</div>

<!-- Add a button for new instances of object -->
<%= render :partial => 'partials/add_new_object', locals: {model_name: model_name} %>

p4-sciencequiz-erinsusanthomas-main/app/views/partials/_nav.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
      <li><%= link_to 'Organizations', organizations_path %></li>
      <li><%= link_to 'Teams', teams_path %></li>
      <li><%= link_to 'Students', students_path %></li>
    </ul>
    <ul class="right">
      <li><%# link_to 'Logout', logout_path %></li>
    </ul>
  </div>
</nav>

p4-sciencequiz-erinsusanthomas-main/app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
      &nbsp;Display All
    <% end %>
    &nbsp;&nbsp;
  
  <% if controller.respond_to?(:update) %>
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if controller.respond_to?(:destroy) %>
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  <% end %>

  <% if controller.respond_to?(:close) %>
    <%= link_to(eval("close_#{model_name}_path(object)"), method: 'patch', data: {confirm: "Are you sure you want to close this #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Close #{opt}" %>
    <% end %>
  <% end %>

  <% if controller.respond_to?(:terminate) %>
    <%= link_to(eval("terminate_#{model_name}_path(object)"), method: 'patch', data: {confirm: "Are you sure you want to terminate this #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Terminate #{opt}" %>
    <% end %>
  <% end %>
</div>

p4-sciencequiz-erinsusanthomas-main/app/views/partials/_show_structure.html.erb
<div class="row">
  <div class="col s7">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s5">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>
<div class="row">
  <%= render :partial => 'partials/display_base_errors', locals: {object: object} %>
  <%= render :partial => 'partials/object_options', locals: {model_name: model_name, object: object} %>
</div>

p4-sciencequiz-erinsusanthomas-main/app/views/partials/_topbar.html.erb
<div class="row valign-wrapper" id="topbar">
  <div class="col s1">
  </div>
  <div class="col s10">
    <h3><%= link_to 'ScienceQuiz Tracking System', home_path %></h3>
  </div>
  <div class="col s1">
    &nbsp;
  </div>
</div>