p4-sciencequiz-erinsusanthomas-main/config/routes.rb
Rails.application.routes.draw do

  # Generated routes
  resources :organizations
  resources :teams
  resources :students

  # Routes for student_teams
  get 'student_teams/new',             to: 'student_teams#new',       as: :new_student_team
  post 'student_teams',                to: 'student_teams#create',    as: :student_teams
  patch 'student_teams/:id/terminate', to: 'student_teams#terminate', as: :terminate_student_team
  delete 'student_teams/:id',          to: 'student_teams#destroy',   as: :remove_student_team

  # Semi-static page routes
  get 'home',         to: 'home#index',   as: :home
  get 'home/about',   to: 'home#about',   as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

p4-sciencequiz-erinsusanthomas-main/app/models/student.rb
class Student < ApplicationRecord
  include AppHelpers::Deletions
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods
  include AppHelpers::Validations

  # Relationships
  belongs_to :organization
  has_many :student_teams
  has_many :teams, through: :student_teams
  has_many :student_quizzes
  has_many :quizzes, through: :student_quizzes

  # Scopes
  scope :alphabetical, -> { order('last_name, first_name') }
  scope :juniors, -> { where('grade < 7') }
  scope :seniors, -> { where('grade > 6') }
  scope :for_organization, ->(organization) { where(organization_id: organization.id) }

  # Validations
  validates_presence_of :first_name, :last_name, :grade, :organization_id
  validates_numericality_of :grade, greater_than: 2, less_than: 13, only_integer: true
  validate -> { is_active_in_system(:organization) }, on: :create

  # Methods
  def name
    "#{last_name}, #{first_name}"
  end
  
  def proper_name
    "#{first_name} #{last_name}"
  end

  def junior?
    grade < 7
  end

  def current_team
    curr_team = self.student_teams.current    
    return nil if curr_team.empty?
    curr_team.first.team   # return as a single object, not an array
  end

  #Callbacks
  before_destroy do 
    if self.student_quizzes.empty?
      self.student_teams.each do |st| 
        st.destroy if st.team = self.current_team
      end
    else
      cannot_destroy_object()
    end
  end

  after_rollback :make_student_inactive
  after_update :when_made_inactive_terminate, on: :make_inactive

  private
  def make_student_inactive
    return true unless self.destroyable == false
    self.make_inactive
    self.student_teams.each do |st| 
      st.terminate_now if st.team = self.current_team 
    end 
    msg = "This #{self.class.to_s.downcase} cannot be deleted but was made inactive instead."
    errors.add(:base, msg)
  end
  def when_made_inactive_terminate
    self.student_teams.each do |st| 
      st.terminate_now if st.team = self.current_team
    end 
  end
end

p4-sciencequiz-erinsusanthomas-main/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @active_students = Student.active.alphabetical.paginate(page: params[:page]).per_page(10)
    @inactive_students = Student.inactive.alphabetical
  end

  def show
    @current_team = @student.current_team # more to come
    @team_history = @student.student_teams.chronological
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = "Successfully created #{@student.proper_name}."
      redirect_to student_path(@student) 
    else
      render action: 'new'
    end      
  end

  def update
    if @student.update_attributes(student_params)
      redirect_to student_path(@student), notice: "Updated all information on #{@student.proper_name}" 
    else
      render :action => "edit"
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path, notice: "Removed #{@student.proper_name} from the system."
  end

  private
  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:first_name, :last_name, :organization_id, :grade, :active)
  end

end

p4-sciencequiz-erinsusanthomas-main/app/views/students/_active_students.html.erb
<% if @active_students.empty? %>
  <h4>No active students at this time</h4>
<% else %>
  <div class="card" id="current_students">
    <div class="card-content">
      <span class="card-title">Active Students in ScienceQuiz</span>
      <table class="striped highlight">
        <thead>
          <th>Student Name</th>
          <th>Organization</th>
          <th>Current Team</th>
          <th class="align_center">Edit</th>
        </thead>
        <% for student in @active_students %>
          <tr>
            <td><%= link_to student.name, student_path(student) %></td>
            <td><%= link_to student.organization.name, organization_path(student.organization) %></td>
            <% if student.current_team.nil? %>
              <td>N/A</td>
            <% else %>
              <td><%= link_to student.current_team.name, team_path(student.current_team) %></td>
            <% end %>
            <td class="align_center">
              <%= link_to edit_student_path(student) do %>
                  <i class="material-icons">edit</i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
      <%= will_paginate @active_students, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
    </div>
  </div>
<% end%>

p4-sciencequiz-erinsusanthomas-main/app/views/students/_inactive_students.html.erb
<% unless @inactive_students.empty? %>
  <div class="card" id="current_teams">
    <div class="card-content">
      <span class="card-title">Inactive Students</span>

          <% for student in @inactive_students %>
              <li>
                  <%= link_to student.name, student_path(student) %>
              </li>
          <% end %>
    </div>
  </div>
<% end%>

p4-sciencequiz-erinsusanthomas-main/app/views/students/_student_data.html.erb
<div class="card">
  <div class="card-content">
    <h5><%= @student.proper_name %></h5><br />

    <b>Organization:&nbsp;&nbsp;</b>
      <%= link_to @student.organization.name, organization_path(@student.organization) %><br><br>

    <b>Current Team:&nbsp;&nbsp;</b>
      <%= @student.current_team.nil? ? "N/A" : link_to(@student.current_team.name, team_path(@student.current_team)) %><br><br>

    <b>Grade:&nbsp;&nbsp;</b>
      <%= @student.grade %><br><br>

    <b>Active?&nbsp;&nbsp;</b>
      <%= @student.active ? "Yes" : "No" %><br><br>

  </div>
</div>

p4-sciencequiz-erinsusanthomas-main/app/views/students/_student_fields.html.erb
<%= f.input :first_name, label_html: { class: 'active' } %>
<%= f.input :last_name, label_html: { class: 'active' } %>
<%= f.input :organization_id, collection: Organization.active.alphabetical.to_a, include_blank: true %>
<%= f.input :grade, label_html: { class: 'active' } %>
<%= f.input :active %>

p4-sciencequiz-erinsusanthomas-main/app/views/students/_student_sidebar.html.erb
<% unless @team_history.empty? %>
  <div class="card" id="current_teams">
    <div class="card-content">
      <span class="card-title">Team History</span>
      <table class="lined">
        <thead>
          <th>Team</th>
          <th>Starting</th>
          <th>Ending</th>
        </thead>
          <% for assignment in @team_history %>
            <tr>
              <td><%= link_to assignment.team.name, team_path(assignment.team) %></td>
              <td><%= assignment.start_date.strftime("%m/%d/%y") %></td>
              <td><%= assignment.end_date.nil? ? "--" : assignment.end_date.strftime("%m/%d/%y") %></td>
            </tr>
          <% end %>
      </table>
      <div class="card-action">
        <%= link_to "Add to a new team", new_student_team_path(student_id: @student.id) %>
      </div>
    </div>
  </div>
<% else%>
    <div class="card grey lighten-3">
      <div class="card-action">
        <%= link_to "Add to a new team", new_student_team_path(student_id: @student.id) %>
      </div>
    </div>
<% end%>

p4-sciencequiz-erinsusanthomas-main/app/views/students/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @student, 
                                                        type_of_form: "Edit Student",
                                                        fields: "student_fields"} %>

p4-sciencequiz-erinsusanthomas-main/app/views/students/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "student", 
                                                         primary: "active_students", 
                                                         secondary: nil,
                                                         sidebar: "inactive_students"} %>

p4-sciencequiz-erinsusanthomas-main/app/views/students/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @student, 
                                                        type_of_form: "New Student",
                                                        fields: "student_fields"} %>

p4-sciencequiz-erinsusanthomas-main/app/views/students/show.html.erb
<%= render partial: "partials/show_structure", locals: {model_name: "student", 
                                                         object: @student,
                                                         primary: "student_data", 
                                                         secondary: nil,
                                                         sidebar: "student_sidebar"} %>