p4-sciencequiz-erinsusanthomas-main/config/routes.rb
Rails.application.routes.draw do

  # Generated routes
  resources :organizations
  resources :teams
  resources :students

  # Routes for student_teams
  get 'student_teams/new',             to: 'student_teams#new',       as: :new_student_team
  post 'student_teams',                to: 'student_teams#create',    as: :student_teams
  patch 'student_teams/:id/terminate', to: 'student_teams#terminate', as: :terminate_student_team
  delete 'student_teams/:id',          to: 'student_teams#destroy',   as: :remove_student_team

  # Semi-static page routes
  get 'home',         to: 'home#index',   as: :home
  get 'home/about',   to: 'home#about',   as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

p4-sciencequiz-erinsusanthomas-main/app/models/organization.rb
class Organization < ApplicationRecord
  include AppHelpers::Deletions
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods

  # Relationships
  has_many :students
  has_many :teams
  has_many :student_teams, through: :teams
  has_many :users
  has_many :events

  # Scopes
  scope :alphabetical, -> { order('name') }

  # Validations
  STATES_LIST = [['Alabama', 'AL'],['Alaska', 'AK'],['Arizona', 'AZ'],['Arkansas', 'AR'],['California', 'CA'],['Colorado', 'CO'],['Connectict', 'CT'],['Delaware', 'DE'],['District of Columbia ', 'DC'],['Florida', 'FL'],['Georgia', 'GA'],['Hawaii', 'HI'],['Idaho', 'ID'],['Illinois', 'IL'],['Indiana', 'IN'],['Iowa', 'IA'],['Kansas', 'KS'],['Kentucky', 'KY'],['Louisiana', 'LA'],['Maine', 'ME'],['Maryland', 'MD'],['Massachusetts', 'MA'],['Michigan', 'MI'],['Minnesota', 'MN'],['Mississippi', 'MS'],['Missouri', 'MO'],['Montana', 'MT'],['Nebraska', 'NE'],['Nevada', 'NV'],['New Hampshire', 'NH'],['New Jersey', 'NJ'],['New Mexico', 'NM'],['New York', 'NY'],['North Carolina','NC'],['North Dakota', 'ND'],['Ohio', 'OH'],['Oklahoma', 'OK'],['Oregon', 'OR'],['Pennsylvania', 'PA'],['Rhode Island', 'RI'],['South Carolina', 'SC'],['South Dakota', 'SD'],['Tennessee', 'TN'],['Texas', 'TX'],['Utah', 'UT'],['Vermont', 'VT'],['Virginia', 'VA'],['Washington', 'WA'],['West Virginia', 'WV'],['Wisconsin', 'WI'],['Wyoming', 'WY']].freeze

  validates_presence_of :name, :street_1, :zip, :short_name
  validates_format_of :zip, with: /\A\d{5}\z/, message: "should be five digits long", allow_blank: false
  validates_inclusion_of :state, in: STATES_LIST.map {|key, value| value}, message: "is not an option", allow_blank: true
  validates_uniqueness_of :short_name, case_sensitive: false

  #Callbacks
  before_destroy do 
    cannot_destroy_object()
  end

end

p4-sciencequiz-erinsusanthomas-main/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  def index
    @active_organizations = Organization.active.alphabetical.paginate(page: params[:page]).per_page(10)
    @inactive_organizations = Organization.inactive.alphabetical
  end

  def show
    # @current_junior_students = @organization.students.juniors.alphabetical.active
    # @current_senior_students = @organization.students.seniors.alphabetical.active
    # @current_junior_teams    = @organization.teams.juniors.alphabetical.active
    # @current_senior_teams    = @organization.teams.seniors.alphabetical.active
    @current_teams           = @organization.teams.active.by_division.alphabetical
    @current_students        = @organization.students.active.alphabetical
  end

  def new
    @organization = Organization.new
  end

  def edit
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      flash[:notice] = "Successfully created #{@organization.name}."
      redirect_to organization_path(@organization) 
    else
      render action: 'new'
    end      
  end

  def update
    if @organization.update_attributes(organization_params)
      redirect_to organization_path(@organization), notice: "Updated all information for #{@organization.short_name}" 
    else
      render :action => "edit"
    end
  end

  def destroy
    @organization.destroy
    redirect_to organizations_path, notice: "Removed #{@organization.name} from the system."
  end

  private
  def set_organization
    @organization = Organization.find(params[:id])
  end

  def organization_params
    params.require(:organization).permit(:name, :street_1, :street_2, :city, :state, :zip, :short_name, :active)
  end

end

p4-sciencequiz-erinsusanthomas-main/app/views/organizations/_active_organizations.html.erb
<% if @active_organizations.empty? %>
  <h4>No active organizations at this time</h4>
<% else %>
  <div class="card" id="current_organizations">
    <div class="card-content">
      <span class="card-title">Active Organizations</span>
      <table class="striped highlight">
        <thead>
          <th>Name</th>
          <th>State</th>
          <th class="align_center">Edit</th>
        </thead>
        <% for organization in @active_organizations %>
          <tr>
            <td><%= link_to organization.name, organization_path(organization) %></td>
            <td><%= organization.state %></td>

            <td class="align_center">
              <%= link_to edit_organization_path(organization) do %>
                  <i class="material-icons">edit</i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
      <%= will_paginate @active_organizations, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
    </div>
  </div>
<% end%>

p4-sciencequiz-erinsusanthomas-main/app/views/organizations/_inactive_organizations.html.erb
<% unless @inactive_organizations.empty? %>
  <div class="card" id="current_teams">
    <div class="card-content">
      <span class="card-title">Inactive Organizations</span>

          <% for organization in @inactive_organizations %>
              <li>
                  <%= link_to organization.name, organization_path(organization) %>
              </li>
          <% end %>
    </div>
  </div>
<% end%>

p4-sciencequiz-erinsusanthomas-main/app/views/organizations/_org_sidebar.html.erb
<%= render partial: "team_stats" %>
<p>&nbsp;</p>
<%= render partial: "student_stats" %>

p4-sciencequiz-erinsusanthomas-main/app/views/organizations/_organization_data.html.erb
<div class="card">
  <div class="card-content">
    <h5><%= @organization.name %></h5><br />

    <b>Short Name:&nbsp;&nbsp;</b>
      <%= @organization.short_name %><br><br>

    <b>Address:&nbsp;&nbsp;</b>
      <%= render partial: "partials/address", locals: { organization: @organization } %>    
      <br />

    <b>Active?&nbsp;&nbsp;</b>
      <%= @organization.active ? "Yes" : "No" %><br><br>

    <b>Joined ScienceQuiz in <%= @organization.created_at.year %></b><br><br><br>

  </div>
</div>

p4-sciencequiz-erinsusanthomas-main/app/views/organizations/_organization_fields.html.erb
<%= f.input :name, label_html: { class: 'active' } %>
<%= f.input :short_name, label_html: { class: 'active' } %>
<%= f.input :street_1, label_html: { class: 'active' } %>
<%= f.input :street_2, label_html: { class: 'active' } %>
<%= f.input :city, label_html: { class: 'active' } %>
<%= f.input :state, collection: Organization::STATES_LIST, include_blank: true %>
<%= f.input :zip, label_html: { class: 'active' } %>
<%= f.input :active %>

p4-sciencequiz-erinsusanthomas-main/app/views/organizations/_student_stats.html.erb
<% unless @current_students.empty? %>
  <div class="card" id="current_teams">
    <div class="card-content">
      <span class="card-title">Current Students - <%= @organization.short_name %></span>
      <table class="lined">
        <thead>
          <th>Name</th>
          <th>Grade</th>
        </thead>
          <% for student in @current_students %>
            <tr>
              <td>
                  <%= link_to student.name, student_path(student) %>
              </td>
              <td><%= student.grade %></td>
            </tr>
          <% end %>
      </table>
      <div class="card-action">
        <%= link_to "Add a new student", new_student_path(organization_id: @organization.id) %>
      </div>
    </div>
  </div>
<% else%>
    <div class="card grey lighten-3">
      <div class="card-action">
        <%= link_to "Add a new student", new_student_path(organization_id: @organization.id) %>
      </div>
    </div>
<% end%>

p4-sciencequiz-erinsusanthomas-main/app/views/organizations/_team_stats.html.erb
<% unless @current_teams.empty? %>
  <div class="card" id="current_teams">
    <div class="card-content">
      <span class="card-title">Current Teams - <%= @organization.short_name %></span>
      <table class="lined">
        <thead>
          <th>Name</th>
          <th>Division</th>
        </thead>
          <% for team in @current_teams %>
            <tr>
              <td>
                  <%= link_to team.name, team_path(team) %>
              </td>
              <td><%= team.division.capitalize %></td>
            </tr>
          <% end %>
      </table>
      <div class="card-action">
        <%= link_to "Add a new team", new_team_path(organization_id: @organization.id) %>
      </div>
    </div>
  </div>
<% else%>
    <div class="card grey lighten-3">
      <div class="card-action">
        <%= link_to "Add a new team", new_team_path(organization_id: @organization.id) %>
      </div>
    </div>
<% end%>

p4-sciencequiz-erinsusanthomas-main/app/views/organizations/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @organization, 
                                                        type_of_form: "Edit Organization",
                                                        fields: "organization_fields"} %>

p4-sciencequiz-erinsusanthomas-main/app/views/organizations/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "organization", 
                                                         primary: "active_organizations", 
                                                         secondary: nil,
                                                         sidebar: "inactive_organizations"} %>

p4-sciencequiz-erinsusanthomas-main/app/views/organizations/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @organization, 
                                                        type_of_form: "New Organization",
                                                        fields: "organization_fields"} %>

p4-sciencequiz-erinsusanthomas-main/app/views/organizations/show.html.erb
<%= render partial: "partials/show_structure", locals: {model_name: "organization", 
                                                         object: @organization,
                                                         primary: "organization_data", 
                                                         secondary: nil,
                                                         sidebar: "org_sidebar"} %>